name: calib-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask=2.3.3
  - flask-wtf=1.2.1
  - numpy=1.26.0
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - joblib=1.3.2
  - werkzeug=2.3.7
  - pip
  - pip:
    - wtforms==3.0.1 